### ISSUE TITLE
Can't build DVM with DMD 2.066.1

### ISSUE THREAD

**Issue by CyberShadow** [jacob-carlborg/dvm#29]
```
[dbuild@freebsd ~/dvm]$ dub build
Fetching tango 1.0.0+2.066 (getting selected version)...
Placing tango 1.0.0+2.066 to /home/dbuild/.dub/packages/...
Fetching mambo 0.0.2 (getting selected version)...
Placing mambo 0.0.2 to /home/dbuild/.dub/packages/...
Building tango 1.0.0+2.066 configuration "static", build type debug.
Running dmd...
tango.io.FileScan is deprecated. Please use tango.io.FilePath.toList or tango.io.vfs.* instead.
tango.math.BigInt is deprecated. Please use std.bigint instead.
Building mambo 0.0.2 configuration "library", build type debug.
Running dmd...
../../../../home/dbuild/.dub/packages/mambo-0.0.2/mambo/arguments/Arguments.d(201): Error: no overload matches for remove(T)(T[] arr, T[] elements...)
FAIL ../../../../home/dbuild/.dub/packages/mambo-0.0.2/.dub/build/library-debug-posix.freebsd-x86_64-dmd_2066-C29A0637BB4AC1545E6B6AA9F861ECD2/ mambo staticLibrary
Error executing command build: dmd failed with exit code 1.
```

**Comment by jacob-carlborg** [comment]
BTW, does DVM work on FreeBSD and what shell do you use?

**Comment by CyberShadow** [comment]
> does DVM work on FreeBSD

Don't know yet.

> and what shell do you use?

FreeBSD defaults to tcsh, but bash is installable, which is what I tried using.

**Comment by jacob-carlborg** [comment]
Please let me know how it goes.

**Comment by CyberShadow** [comment]
Thanks for the quick fix. I'll give it a go later today.

**Comment by jacob-carlborg** [comment]
Cool, fortunately Dicebot had already fixed this problem due to DStep using the same dependency :smiley:

**Comment by CyberShadow** [comment]
Seems to work fine. `.bash_profile` doesn't exist by default, but DVM handles it OK, and works after I manually set it up. The one oddity I noticed is that the "use" command doesn't stick across sessions - after logging in again, I have to run `dvm use 2.066.1` before I can run dmd. Not a big deal, since I can just stick the command in `.bash_profile`.

**Comment by jacob-carlborg** [comment]
> Seems to work fine. .bash_profile doesn't exist by default, but DVM handles it OK, and works after I manually set it up.

Is there a file that exists by default that can be used?

> The one oddity I noticed is that the "use" command doesn't stick across sessions - after logging in again, I have to run dvm use 2.066.1 before I can run dmd

That is by design. You can use one version of DMD in one terminal session and another in a different session. Use `dvm use 2.066.1 -d` to set it as the default version.

**Comment by CyberShadow** [comment]
> Is there a file that exists by default that can be used?

There is the standard `.profile` file. It is read by all shells, so I guess it has to be written in the POSIX shell subset.

> Use dvm use 2.066.1 -d to set it as the default version.

Oh, right! I had used that switch on other machines and had forgotten about it. Thanks.

**Comment by jacob-carlborg** [comment]
> There is the standard .profile file.

Right, I haven't not seen it exist by default on either OS X or Linux, but I guess DVM could create it if it doesn't exist.

> It is read by all shells, so I guess it has to be written in the POSIX shell subset.

It already is, DVM uses `/bin/sh`.
