### ISSUE TITLE
DVM should download from downloads.dlang.org instead of ftp.digitalmars.com

### ISSUE THREAD

**Issue by Hackerpilot** [jacob-carlborg/dvm#30]
CC @MartinNowak

**Comment by MartinNowak** [comment]
Yep, it's all there, the server is more reliable and we get usage stats.
If you're really nice and there are many users of dvm you use a custom user-agent so we can filter our stats.

**Comment by jacob-carlborg** [comment]
I guess I can add `downloads.dlang.org` as a first try. The reason for why I'm still using `ftp.digitalmars.com` is that has been the only stable place to download DMD for all these years.

> If you're really nice and there are many users of dvm you use a custom user-agent so we can filter our stats.

Sure, I can do that.

**Comment by jcrapuchettes** [comment]
:+1:

**Comment by jacob-carlborg** [comment]
Setting user agent is fixed as well in https://github.com/jacob-carlborg/dvm/commit/e62863edd2da31dbe3b4958af273c5298e51a0af.
