### ISSUE TITLE
Doesn't compile with recent compilers (e.g. dmd-2.074.1)

### ISSUE THREAD

**Issue by MartinNowak** [jacob-carlborg/dvm#43]
Due to compilation errors in mambo/tango.
Tried v0.4.4 and v0.4.4-4-g5d662b4.

**Comment by jacob-carlborg** [comment]
Yes. The pre-compiled binaries should work.

**Comment by jacob-carlborg** [comment]
BTW, do you know what to do instead of `__va_argsave`?

**Comment by jacob-carlborg** [comment]
Fixed in https://github.com/jacob-carlborg/dvm/commit/f8fd8eea93598e31dc70d8aed145848fbd29787b.
