### ISSUE TITLE
dmd version used by dvm still uses global include path

### ISSUE THREAD

**Issue by FreeSlave** [jacob-carlborg/dvm#45]
Using dvm 0.5.0.
After I use `dvm use` dmd reports the intended version, yet it uses the global include path to import library modules (/usr/include/dmd/phobos/).

**Comment by jacob-carlborg** [comment]
Hmm, which config file is DMD using? You can find out by running `dmd | head`.

**Comment by FreeSlave** [comment]
Oh, it's my mistake.
I needed to pass a path to the chosen dmd to dub.
I thought dub will pick the first found dmd in PATH, but it seems, the search is more complicated than that.
Probably the thing should be mentioned on README.

**Comment by jacob-carlborg** [comment]
> I thought dub will pick the first found dmd in PATH, but it seems, the search is more complicated than that.

Hmm, I thought it would too. I always use Dub and DMD through DVM. But I don't have a globally installed DMD. It's a possibility that it's using the correct version of DMD but picking up the wrong `dmd.conf` file. To know for sure which version of DMD you're compiling with you can add `pragma(msg, __VERSION__);` to the source code.

Also, if you're running Dub through a shell script you need to manually setup DVM:

```bash
if [ -s "$HOME/.dvm/scripts/dvm" ] ; then
    . "$HOME/.dvm/scripts/dvm" ;
    dvm use 2.086.0
fi
```

**Comment by FreeSlave** [comment]
@jacob-carlborg I have this `if` statement in my .bashrc (minus `dvm use` which I do in the bash separately).
I checked, dub really uses the globally installed dmd version even if some other dmd version is in PATH before the global one.
