### ISSUE TITLE
macOS Cataline

### ISSUE THREAD

**Issue by joelcnz** [jacob-carlborg/dvm#47]
Ok, I've had a go at using your DVM:

1. Executed this in the terminal: 'curl -L -o dvm https://github.com/jacob-carlborg/dvm/releases/download/v0.5.1/dvm-0.5.1-macos && chmod +x dvm && ./dvm install dvm'

2. Closed and opened a new terminal. Tried running dvm, but it wasn't found. I think macOS the terminal is new. I did get it to run with it in the same directory.

3. 'dvm install 2.088.0' looks like it's been installed but it says 'zsh: command not found: dmd' I've tried 87.1 too, some problem.

I get this with use:
joelchristensen@Joel-Computer ~ % ./dvm use dmd-2.088.0
An unknown error occurred:
tango.core.Exception.IOException@../../../.dub/packages/tango-d2port/tango/tango/core/Exception.d(59): File not found "/Users/joelchristensen/.dvm/env/dmd-dmd-2.088.0"
----------------
??:? void dvm.commands.Use.Use.writeShellScript(dvm.dvm.ShellScript.ShellScript, immutable(char)[]) [0x10b0678fe]
??:? void dvm.commands.Use.Use.loadEnvironment() [0x10b065a6c]
??:? void dvm.commands.Use.Use.execute() [0x10b065514]
??:? void dvm.commands.Command.Command.invoke(immutable(char)[][]...) [0x10b046a73]
??:? void dvm.dvm.Application.Application.handleCommand(immutable(char)[], immutable(char)[][]) [0x10b0695aa]
??:? void dvm.dvm.Application.Application.handleArgs(immutable(char)[][]) [0x10b069527]
??:? void dvm.dvm.Application.Application.parseOptions().__lambda12(immutable(char)[][]) [0x10b069da2]
??:? dvm.util.OptionParser.OptionParser dvm.util.OptionParser.OptionParser.parse(immutable(char)[][], bool) [0x10b0774f9]
??:? void dvm.dvm.Application.Application.parseOptions() [0x10b069b68]
??:? int dvm.dvm.Application.Application.run(immutable(char)[][]).__lambda2() [0x10b069139]
??:? int dvm.dvm.Application.Application.handleExceptions().__lambda1(int delegate()) [0x10b06919a]
??:? int mambo.util.Use.Use!(int delegate()).Use.opIn(int delegate()) [0x10b090297]
??:? int dvm.dvm.Application.Application.run(immutable(char)[][]) [0x10b069110]
??:? dvm [0x10b046945]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll().__lambda1() [0x10b107bf6]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x10b107aa0]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).runAll() [0x10b107b7a]
??:? void rt.dmain2._d_run_main2(char[][], ulong, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x10b107aa0]
??:? _d_run_main2 [0x10b107a03]
??:? _d_run_main [0x10b1077b1]
??:? dvm [0x10b046971]
??:? start [0x7fff64832404]
??:? 0x0 [0x2]
joelchristensen@Joel-Computer ~ % 

I know you've said you don't have much time for D related stuff, that was a while ago, is that still true?

**Comment by jacob-carlborg** [comment]
I have only tested DVM with Bash. I’m still using Bash on macOS Catalina.

You can verify if DVM has been properly installed by running: `type dvm | head -n 1`. This should give back: `dvm is a function` if it’s been properly installed.

If you want to continue to use zsh you can try to manually install DVM by adding `. ~/.dvm/scripts/dvm` to the zsh file that corresponds to `~/.bash_profile`. 

Yes, I still don’t have that much time to work on D.

**Comment by joelcnz** [comment]
Thanks for your time.

I'm still getting the same errors with Bash. I know DVM isn't installed properly, at all, because entering 'dvm' comes up with command not found. The executable file runs, though, and shows 3 versions of DMD.

Do you know if I can use Home Brew with DMG (from the front page of dlang.org)?

**Comment by jacob-carlborg** [comment]
> I'm still getting the same errors with Bash. I know DVM isn't installed properly, at all, because entering 'dvm' comes up with command not found. The executable file runs, though, and shows 3 versions of DMD.

Did you run `dvm install dvm`?

> Do you know if I can use Home Brew with DMG (from the front page of dlang.org)?

The installer (packaged in the DMG) will install DMD in `/Library/D/dmd` and create symlinks to `/usr/local/bin`. That might cause a conflict with Homebrew.

**Comment by jacob-carlborg** [comment]
> The executable file runs, though, and shows 3 versions of DMD.

Yes, but I don't think switching compiler, the `use` command, will work if DVM is not properly installed.

**Comment by joelcnz** [comment]
I've gone ahead with using the DMG package. I uninstalled the brew dmd and dub. I think I can uninstall the DMG package, if I wanted to go back to brew. I'm still using brew with libraries - they still work. Do you think it was a bad idea to use the DMG package?

**Comment by jacob-carlborg** [comment]
No, it’s not a bad idea, but it wouldn’t be my first choice. I would pick DVM over both the DMG and brew. With DVM you don’t need to wait for someone to repack a release for it to be available. It uses the official ZIP package. It also allows you to easily have multiple versions of DMD installed and switch between them. You can have one terminal session with one version and another session with another version. It’s also perfect to try new versions of DMD. If you encounter a regression you can easily switch back to the previous version, you don’t even need to uninstall it. 

But if you still want to use zsh then DVM might not work.

**Comment by joelcnz** [comment]
Thanks for your replies.

I still can't install DVM, even with the old terminal. './dvm install dvm' says nothing, and 'dvm' says command not found.

**Comment by jacob-carlborg** [comment]
Did you open a new shell after trying the`dvm` command?

**Comment by joelcnz** [comment]
Yes, I did open a new shell.

**Comment by jacob-carlborg** [comment]
Ok, I did some debugging and it looks like the `.bash_profile` file needs to exist for the installation to work. That's a bug, DVM should be able to create the `.bash_profile` file if it doesn't exist.

**Comment by joelcnz** [comment]
Ok, I've uninstalled the DMG installation of D. And dvm seems to be working with the latest D compiler, (by following your instructions). Thanks.

**Comment by joelcnz** [comment]
I'm going back to DMG, dvm with D has problems like not working with Visual Code.

**Comment by jacob-carlborg** [comment]
> Maybe go back to it if I can get Visual Code

I think the problem with Visual Studio Code is that DVM doesn't install the D compiler in a path that is located in `$PATH` by default. What you need to do is to configure Visual Studio Code to point to the location of DMD. Either something like `~/.dvm/compilers/dmd-2.088.0/osx/bin/dmd` for a specific version, `~/.dvm/bin/dvm-default-dc` which is the default compiler (selected using `dvm use <version> -d`) or `~/.dvm/bin/dvm-current-dc` which basically is the latest selected compiler (using `dvm use <version>`).
